"""
Django settings for avisaje2 project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8tl@s=q_w+e_5u$gw)_i_c57m0h&$sz!p!ltx5#m3&0&qm90+z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'avisaje_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'avisaje2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'avisaje2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FROM_EMAIL= 'smartanalytics@smartanalytic.cl'


# DKIM settings
DKIM_DOMAIN = 'smartanalytic.cl'  # Replace with your domain name
DKIM_SELECTOR = 'my_dkim'  # Replace with your DKIM selector
DKIM_PRIVATE_KEY = '''
MIIEowIBAAKCAQEAyY94F0NM0Bv/26CAxAYkRDiHg1e+mPaKToFTxkKHU1W/R5Bq
OTMMuHrKYfByWiXc7YpvPlpSQL+D24BNlRtxleM0QAGO/UL0bjdm2w7EX8Fm0zlh
O1uFJ2ExxF5xEvDrMdQVLnem7zLX32dLsgpRuDp52cZ9SOYjxf2yCtqBND9DJkD4
8BFg9f2RaoUqnI/zbW/nqk107cABtBOyGd7VuFdNg1HHOtW2cYxDmQntVZWGyoR+
NmD7DrOPXp8PzM0yQMSOceC7nKhmQ0MmOe24F715z9fX4q2jop5/E8aAiJdjWgZR
tr/AQApCp/SoSop/VBFVpjRGAAhUg6L5VwMQowIDAQABAoIBAQCaV4oWBirjkQ0z
GIyBjlJnCwJ5yM7iQqdVxiJoRrlpTtfR7PvqIPU0rpIavQxTi3rJSqA0luU1P3Gw
u2atLv6jT//Ko2bi+EpDu5i/VWd6C5a5V87krQghR4PcYpUjc+gll8lAc88Yi05S
e76y7sP01pJH+H4nPFNYYRPcy8T0Q8DzkyDn9bEMvHFoMrQekUlISNvuCH4Vz7ZJ
EqjaOigsaAd3u8CvERTLi2rir70m6UgSflbd7YL1aTKV/ebDbs3A+prX8ODjuCCy
G/UXhMLbCvGEW8rK5pBMnHzHRuctpxQROZMkz7iRI+2840IalHZ/nKqEQ63sMt1F
5Ay3OImBAoGBAOyK+8Gmc9SJFHTtGVlazGJeC02KlqaCqv4q6qgX7qtxCNAHH9Mw
YsKUYYVxeynVI/Y9iDR8d02KmMCyqiX42GCiOEdQoYneR+7Ai2pmEUNF2zmxa9LP
rFtVBLVhR7bycw32Y1Jx2EUkffQLHUQuovb1eNEizK0KKxpj9z2Rzkz7AoGBANoj
1wwixYl5iJsEew7p/shPASr2rXsNb04XYLGhHzTlfAOg02+EVsYslPAdi76ch1y+
ag85VuvRViUR+o/LcIHgx8zE4A/4caqC8FdLlnSTdLwFYOIQ6rLCfxdW0VASigXZ
bQY3Dhmwr15R/bd0JH8/hfqnKczfAbQZtLLGhqp5AoGAFAGhT3yrmVNKxqTzGuqi
FMPNgu5w1X6BxeONW1BC4H879pRTrcIO6FQyd13kw+ICG6aSqZXJZWaOiuXRnEqS
yoGN7wIz13xUay4f3IzrctwqsZN/AiKMemETd9/Vd/TDpG+tcOCuIRL4EDcMb6Le
J7MVV+LwmsYcZSwFUlDNuRcCgYA/ryjwHRKogPe1sggvIXdFiXMg1OVuwExXcxHC
qfRPYBPlh0VTEEK5Fnjg5O9QVahbFigmi6nprLLGncoVwuH0uOf7yxpS70hX7GQ4
SBQDsqzo23UeaqvqRkgOS0VOaCsta/2dS+Ns8p0wHyXAMkMZdzUpKTZV3mFD8CFF
9BmKmQKBgGFJct1wdm+f+vwbZitOe19M07LAoicT3z1BSRYjZxJzURuPLWyGysxp
rVSABlL3Abmcu4mwKyM/cbSkg13uLFwnGs7Z3iNujaNjI6g+x97/WXzSRJJlbpDy
/NMjZDXOZHXTtuTh18a5TjJzaeGbLIMAfL7uK8Qswv5hlvXvqaTm
''' # Replace with the path to your private key file



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'voda9.vodahost9.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'smartanalytics@smartanalytic.cl'
EMAIL_HOST_PASSWORD = 'r}!u}m;,bN.5'
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'smartanalytics@smartanalytic.cl'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'avisaje_app/static'),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

